
name: Bigfastapi CI/CD

on:
  push:
    branches: [ dev ]
 

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

#       - name: Install Dependencies and Build
#         run: |
#           git pull origin dev
#           python3.9 -m venv env
#           source env/bin/activate
#           pip install -r requirements.txt
#           python setup.py bdist_wheel
#           cp .env.sample .env
#           python main.py
          

      - name: Deployment
        run: |
          cd ${{ secrets.API_PATH }}
          source env/bin/activate
          bash deploy.sh > deploy.log
          cat deploy.log
          
          
